// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file messages.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ProtoInput } from "./types_pb";
import { file_types } from "./types_pb";
import type { ProtoLatencyTracker } from "./latency_tracker_pb";
import { file_latency_tracker } from "./latency_tracker_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file messages.proto.
 */
export const file_messages: GenFile = /*@__PURE__*/
  fileDesc("Cg5tZXNzYWdlcy5wcm90bxIFcHJvdG8iVQoQUHJvdG9NZXNzYWdlQmFzZRIUCgxwYXlsb2FkX3R5cGUYASABKAkSKwoHbGF0ZW5jeRgCIAEoCzIaLnByb3RvLlByb3RvTGF0ZW5jeVRyYWNrZXIiYwoRUHJvdG9NZXNzYWdlSW5wdXQSLQoMbWVzc2FnZV9iYXNlGAEgASgLMhcucHJvdG8uUHJvdG9NZXNzYWdlQmFzZRIfCgRkYXRhGAIgASgLMhEucHJvdG8uUHJvdG9JbnB1dEIWWhRyZWxheS9pbnRlcm5hbC9wcm90b2IGcHJvdG8z", [file_types, file_latency_tracker]);

/**
 * @generated from message proto.ProtoMessageBase
 */
export type ProtoMessageBase = Message<"proto.ProtoMessageBase"> & {
  /**
   * @generated from field: string payload_type = 1;
   */
  payloadType: string;

  /**
   * @generated from field: proto.ProtoLatencyTracker latency = 2;
   */
  latency?: ProtoLatencyTracker;
};

/**
 * Describes the message proto.ProtoMessageBase.
 * Use `create(ProtoMessageBaseSchema)` to create a new message.
 */
export const ProtoMessageBaseSchema: GenMessage<ProtoMessageBase> = /*@__PURE__*/
  messageDesc(file_messages, 0);

/**
 * @generated from message proto.ProtoMessageInput
 */
export type ProtoMessageInput = Message<"proto.ProtoMessageInput"> & {
  /**
   * @generated from field: proto.ProtoMessageBase message_base = 1;
   */
  messageBase?: ProtoMessageBase;

  /**
   * @generated from field: proto.ProtoInput data = 2;
   */
  data?: ProtoInput;
};

/**
 * Describes the message proto.ProtoMessageInput.
 * Use `create(ProtoMessageInputSchema)` to create a new message.
 */
export const ProtoMessageInputSchema: GenMessage<ProtoMessageInput> = /*@__PURE__*/
  messageDesc(file_messages, 1);

