// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MouseMove message
type ProtoMouseMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Fixed value "MouseMove"
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseMove) Reset() {
	*x = ProtoMouseMove{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseMove) ProtoMessage() {}

func (x *ProtoMouseMove) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseMove.ProtoReflect.Descriptor instead.
func (*ProtoMouseMove) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoMouseMove) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProtoMouseMove) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ProtoMouseMove) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// MouseMoveAbs message
type ProtoMouseMoveAbs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Fixed value "MouseMoveAbs"
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseMoveAbs) Reset() {
	*x = ProtoMouseMoveAbs{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseMoveAbs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseMoveAbs) ProtoMessage() {}

func (x *ProtoMouseMoveAbs) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseMoveAbs.ProtoReflect.Descriptor instead.
func (*ProtoMouseMoveAbs) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoMouseMoveAbs) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProtoMouseMoveAbs) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ProtoMouseMoveAbs) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// MouseWheel message
type ProtoMouseWheel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Fixed value "MouseWheel"
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseWheel) Reset() {
	*x = ProtoMouseWheel{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseWheel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseWheel) ProtoMessage() {}

func (x *ProtoMouseWheel) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseWheel.ProtoReflect.Descriptor instead.
func (*ProtoMouseWheel) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoMouseWheel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProtoMouseWheel) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ProtoMouseWheel) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// MouseKeyDown message
type ProtoMouseKeyDown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Fixed value "MouseKeyDown"
	Key           int32                  `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseKeyDown) Reset() {
	*x = ProtoMouseKeyDown{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseKeyDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseKeyDown) ProtoMessage() {}

func (x *ProtoMouseKeyDown) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseKeyDown.ProtoReflect.Descriptor instead.
func (*ProtoMouseKeyDown) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoMouseKeyDown) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProtoMouseKeyDown) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

// MouseKeyUp message
type ProtoMouseKeyUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Fixed value "MouseKeyUp"
	Key           int32                  `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMouseKeyUp) Reset() {
	*x = ProtoMouseKeyUp{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMouseKeyUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMouseKeyUp) ProtoMessage() {}

func (x *ProtoMouseKeyUp) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMouseKeyUp.ProtoReflect.Descriptor instead.
func (*ProtoMouseKeyUp) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *ProtoMouseKeyUp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProtoMouseKeyUp) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

// KeyDown message
type ProtoKeyDown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Fixed value "KeyDown"
	Key           int32                  `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoKeyDown) Reset() {
	*x = ProtoKeyDown{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoKeyDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoKeyDown) ProtoMessage() {}

func (x *ProtoKeyDown) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoKeyDown.ProtoReflect.Descriptor instead.
func (*ProtoKeyDown) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *ProtoKeyDown) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProtoKeyDown) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

// KeyUp message
type ProtoKeyUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Fixed value "KeyUp"
	Key           int32                  `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoKeyUp) Reset() {
	*x = ProtoKeyUp{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoKeyUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoKeyUp) ProtoMessage() {}

func (x *ProtoKeyUp) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoKeyUp.ProtoReflect.Descriptor instead.
func (*ProtoKeyUp) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *ProtoKeyUp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProtoKeyUp) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

// Union of all Input types
type ProtoInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to InputType:
	//
	//	*ProtoInput_MouseMove
	//	*ProtoInput_MouseMoveAbs
	//	*ProtoInput_MouseWheel
	//	*ProtoInput_MouseKeyDown
	//	*ProtoInput_MouseKeyUp
	//	*ProtoInput_KeyDown
	//	*ProtoInput_KeyUp
	InputType     isProtoInput_InputType `protobuf_oneof:"input_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoInput) Reset() {
	*x = ProtoInput{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoInput) ProtoMessage() {}

func (x *ProtoInput) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoInput.ProtoReflect.Descriptor instead.
func (*ProtoInput) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *ProtoInput) GetInputType() isProtoInput_InputType {
	if x != nil {
		return x.InputType
	}
	return nil
}

func (x *ProtoInput) GetMouseMove() *ProtoMouseMove {
	if x != nil {
		if x, ok := x.InputType.(*ProtoInput_MouseMove); ok {
			return x.MouseMove
		}
	}
	return nil
}

func (x *ProtoInput) GetMouseMoveAbs() *ProtoMouseMoveAbs {
	if x != nil {
		if x, ok := x.InputType.(*ProtoInput_MouseMoveAbs); ok {
			return x.MouseMoveAbs
		}
	}
	return nil
}

func (x *ProtoInput) GetMouseWheel() *ProtoMouseWheel {
	if x != nil {
		if x, ok := x.InputType.(*ProtoInput_MouseWheel); ok {
			return x.MouseWheel
		}
	}
	return nil
}

func (x *ProtoInput) GetMouseKeyDown() *ProtoMouseKeyDown {
	if x != nil {
		if x, ok := x.InputType.(*ProtoInput_MouseKeyDown); ok {
			return x.MouseKeyDown
		}
	}
	return nil
}

func (x *ProtoInput) GetMouseKeyUp() *ProtoMouseKeyUp {
	if x != nil {
		if x, ok := x.InputType.(*ProtoInput_MouseKeyUp); ok {
			return x.MouseKeyUp
		}
	}
	return nil
}

func (x *ProtoInput) GetKeyDown() *ProtoKeyDown {
	if x != nil {
		if x, ok := x.InputType.(*ProtoInput_KeyDown); ok {
			return x.KeyDown
		}
	}
	return nil
}

func (x *ProtoInput) GetKeyUp() *ProtoKeyUp {
	if x != nil {
		if x, ok := x.InputType.(*ProtoInput_KeyUp); ok {
			return x.KeyUp
		}
	}
	return nil
}

type isProtoInput_InputType interface {
	isProtoInput_InputType()
}

type ProtoInput_MouseMove struct {
	MouseMove *ProtoMouseMove `protobuf:"bytes,1,opt,name=mouse_move,json=mouseMove,proto3,oneof"`
}

type ProtoInput_MouseMoveAbs struct {
	MouseMoveAbs *ProtoMouseMoveAbs `protobuf:"bytes,2,opt,name=mouse_move_abs,json=mouseMoveAbs,proto3,oneof"`
}

type ProtoInput_MouseWheel struct {
	MouseWheel *ProtoMouseWheel `protobuf:"bytes,3,opt,name=mouse_wheel,json=mouseWheel,proto3,oneof"`
}

type ProtoInput_MouseKeyDown struct {
	MouseKeyDown *ProtoMouseKeyDown `protobuf:"bytes,4,opt,name=mouse_key_down,json=mouseKeyDown,proto3,oneof"`
}

type ProtoInput_MouseKeyUp struct {
	MouseKeyUp *ProtoMouseKeyUp `protobuf:"bytes,5,opt,name=mouse_key_up,json=mouseKeyUp,proto3,oneof"`
}

type ProtoInput_KeyDown struct {
	KeyDown *ProtoKeyDown `protobuf:"bytes,6,opt,name=key_down,json=keyDown,proto3,oneof"`
}

type ProtoInput_KeyUp struct {
	KeyUp *ProtoKeyUp `protobuf:"bytes,7,opt,name=key_up,json=keyUp,proto3,oneof"`
}

func (*ProtoInput_MouseMove) isProtoInput_InputType() {}

func (*ProtoInput_MouseMoveAbs) isProtoInput_InputType() {}

func (*ProtoInput_MouseWheel) isProtoInput_InputType() {}

func (*ProtoInput_MouseKeyDown) isProtoInput_InputType() {}

func (*ProtoInput_MouseKeyUp) isProtoInput_InputType() {}

func (*ProtoInput_KeyDown) isProtoInput_InputType() {}

func (*ProtoInput_KeyUp) isProtoInput_InputType() {}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\x05proto\"@\n" +
	"\x0eProtoMouseMove\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"C\n" +
	"\x11ProtoMouseMoveAbs\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"A\n" +
	"\x0fProtoMouseWheel\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"9\n" +
	"\x11ProtoMouseKeyDown\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\x05R\x03key\"7\n" +
	"\x0fProtoMouseKeyUp\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\x05R\x03key\"4\n" +
	"\fProtoKeyDown\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\x05R\x03key\"2\n" +
	"\n" +
	"ProtoKeyUp\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\x05R\x03key\"\xab\x03\n" +
	"\n" +
	"ProtoInput\x126\n" +
	"\n" +
	"mouse_move\x18\x01 \x01(\v2\x15.proto.ProtoMouseMoveH\x00R\tmouseMove\x12@\n" +
	"\x0emouse_move_abs\x18\x02 \x01(\v2\x18.proto.ProtoMouseMoveAbsH\x00R\fmouseMoveAbs\x129\n" +
	"\vmouse_wheel\x18\x03 \x01(\v2\x16.proto.ProtoMouseWheelH\x00R\n" +
	"mouseWheel\x12@\n" +
	"\x0emouse_key_down\x18\x04 \x01(\v2\x18.proto.ProtoMouseKeyDownH\x00R\fmouseKeyDown\x12:\n" +
	"\fmouse_key_up\x18\x05 \x01(\v2\x16.proto.ProtoMouseKeyUpH\x00R\n" +
	"mouseKeyUp\x120\n" +
	"\bkey_down\x18\x06 \x01(\v2\x13.proto.ProtoKeyDownH\x00R\akeyDown\x12*\n" +
	"\x06key_up\x18\a \x01(\v2\x11.proto.ProtoKeyUpH\x00R\x05keyUpB\f\n" +
	"\n" +
	"input_typeB\x16Z\x14relay/internal/protob\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_types_proto_goTypes = []any{
	(*ProtoMouseMove)(nil),    // 0: proto.ProtoMouseMove
	(*ProtoMouseMoveAbs)(nil), // 1: proto.ProtoMouseMoveAbs
	(*ProtoMouseWheel)(nil),   // 2: proto.ProtoMouseWheel
	(*ProtoMouseKeyDown)(nil), // 3: proto.ProtoMouseKeyDown
	(*ProtoMouseKeyUp)(nil),   // 4: proto.ProtoMouseKeyUp
	(*ProtoKeyDown)(nil),      // 5: proto.ProtoKeyDown
	(*ProtoKeyUp)(nil),        // 6: proto.ProtoKeyUp
	(*ProtoInput)(nil),        // 7: proto.ProtoInput
}
var file_types_proto_depIdxs = []int32{
	0, // 0: proto.ProtoInput.mouse_move:type_name -> proto.ProtoMouseMove
	1, // 1: proto.ProtoInput.mouse_move_abs:type_name -> proto.ProtoMouseMoveAbs
	2, // 2: proto.ProtoInput.mouse_wheel:type_name -> proto.ProtoMouseWheel
	3, // 3: proto.ProtoInput.mouse_key_down:type_name -> proto.ProtoMouseKeyDown
	4, // 4: proto.ProtoInput.mouse_key_up:type_name -> proto.ProtoMouseKeyUp
	5, // 5: proto.ProtoInput.key_down:type_name -> proto.ProtoKeyDown
	6, // 6: proto.ProtoInput.key_up:type_name -> proto.ProtoKeyUp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	file_types_proto_msgTypes[7].OneofWrappers = []any{
		(*ProtoInput_MouseMove)(nil),
		(*ProtoInput_MouseMoveAbs)(nil),
		(*ProtoInput_MouseWheel)(nil),
		(*ProtoInput_MouseKeyDown)(nil),
		(*ProtoInput_MouseKeyUp)(nil),
		(*ProtoInput_KeyDown)(nil),
		(*ProtoInput_KeyUp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
